const views={overview:["Resumen de accesos","Visibilidad centralizada para decidir dónde actuar primero."],people:["Sitios por usuario","Investiga rápidamente todos los accesos de una persona."],apps:["Aplicaciones y riesgo","Prioriza aplicaciones según exposición y señales observadas."]};
const people=[
 {user:"Ana Torres",app:"Google Workspace",type:"Directorio",status:"Activo",date:"12 jul 2026"},{user:"Ana Torres",app:"Miro",type:"OAuth",status:"Revisión",date:"10 jul 2026"},{user:"Diego Soto",app:"Portal tributario",type:"Acceso fiscal",status:"Activo",date:"11 jul 2026"},{user:"Elena Ruiz",app:"Canva",type:"OAuth",status:"Revocado",date:"03 jul 2026"},{user:"Elena Ruiz",app:"Google Workspace",type:"Directorio",status:"Activo",date:"12 jul 2026"},{user:"Marco Silva",app:"CRM Comercial",type:"OAuth",status:"Revisión",date:"09 jul 2026"},{user:"Sofía Díaz",app:"Correo corporativo",type:"Directorio",status:"Activo",date:"12 jul 2026"},{user:"Tomás Vega",app:"Gestor documental",type:"OAuth",status:"Revocado",date:"28 jun 2026"}
];
const apps=[
 {app:"Miro",users:12,states:"10 activos · 2 revisión",risk:"Alto",reason:"Exposición amplia y permisos de edición"},{app:"CRM Comercial",users:8,states:"7 activos · 1 revisión",risk:"Medio",reason:"Una cuenta requiere validación"},{app:"Google Workspace",users:24,states:"24 activos",risk:"Bajo",reason:"Segundo factor habilitado"},{app:"Canva",users:6,states:"5 activos · 1 revocado",risk:"Medio",reason:"Acceso revocado pendiente de confirmar"},{app:"Gestor documental",users:4,states:"3 activos · 1 revocado",risk:"Alto",reason:"Permisos sensibles y baja pendiente"}
];
const indicators={users:{label:"Usuarios identificados",value:24,note:"Personas consolidadas",kind:"KPI",rows:[["24 personas","Directorio","Activo","Fuentes consolidadas"],["8 áreas","Organización","Activo","Cobertura completa"]]},relations:{label:"Relaciones de acceso",value:58,note:"Usuario y aplicación",kind:"KPI",rows:[["58 relaciones","Acceso","Activo","Trazabilidad disponible"],["5 fuentes","Inventario","Activo","Vista centralizada"]]},revoked:{label:"Accesos revocados",value:4,note:"Requieren confirmación",kind:"KRI",rows:[["Canva","OAuth","Revocado","Validar cierre"],["Gestor documental","OAuth","Revocado","Prioridad alta"]]},high:{label:"Aplicaciones KRI alto",value:2,note:"Según exposición",kind:"KRI",rows:[["Miro","OAuth","Revisión","12 usuarios expuestos"],["Gestor documental","OAuth","Revisión","Permisos sensibles"]]}};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const cls=s=>s==="Activo"?"ok":s==="Revocado"?"bad":"warn";const risk=r=>r==="Alto"?"high":r==="Medio"?"medium":"low";
function show(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#title').textContent=views[id][0];$('#subtitle').textContent=views[id][1];history.replaceState(null,'',`#${id}`);window.scrollTo({top:0,behavior:'smooth'});}
function renderIndicators(){const box=$('#metrics');box.innerHTML=Object.entries(indicators).map(([id,x])=>`<button class="metric" data-indicator="${id}"><span>${x.label}</span><strong>${x.value}</strong><small>${x.note}</small></button>`).join('');$$('[data-indicator]').forEach(b=>b.onclick=()=>selectIndicator(b.dataset.indicator));selectIndicator('users');}
function selectIndicator(id){const x=indicators[id];$$('[data-indicator]').forEach(b=>b.classList.toggle('active',b.dataset.indicator===id));$('#detail-kind').textContent=`${x.kind} SELECCIONADO`;$('#detail-title').textContent=x.label;$('#detail-text').textContent=x.note;$('#detail-total').textContent=`${x.value} registros`;$('#detail-body').innerHTML=x.rows.map(r=>`<tr><td><strong>${r[0]}</strong></td><td>${r[1]}</td><td><span class="badge ${cls(r[2])}">${r[2]}</span></td><td>${r[3]}</td></tr>`).join('');}
function renderPeople(){const q=$('#people-search').value.toLowerCase(),s=$('#people-status').value;const rows=people.filter(x=>(!q||Object.values(x).join(' ').toLowerCase().includes(q))&&(!s||x.status===s));$('#people-count').textContent=`${rows.length} accesos`;$('#people-body').innerHTML=rows.map(x=>`<tr><td><strong>${x.user}</strong></td><td>${x.app}</td><td><span class="badge info">${x.type}</span></td><td><span class="badge ${cls(x.status)}">${x.status}</span></td><td class="muted">${x.date}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No hay resultados para estos filtros.</td></tr>';}
function renderApps(){const q=$('#apps-search').value.toLowerCase(),r=$('#apps-risk').value;const rows=apps.filter(x=>(!q||Object.values(x).join(' ').toLowerCase().includes(q))&&(!r||x.risk===r));$('#apps-count').textContent=`${rows.length} aplicaciones`;$('#apps-body').innerHTML=rows.map(x=>`<tr><td><strong>${x.app}</strong></td><td>${x.users}</td><td>${x.states}</td><td><span class="badge ${risk(x.risk)}">${x.risk}</span></td><td>${x.reason}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No hay resultados para estos filtros.</td></tr>';}
$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#people-search').oninput=renderPeople;$('#people-status').onchange=renderPeople;$('#apps-search').oninput=renderApps;$('#apps-risk').onchange=renderApps;$('#finish').onclick=()=>{$('#status').textContent='Recorrido completado';$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),3500)};renderIndicators();renderPeople();renderApps();show(views[location.hash.slice(1)]?location.hash.slice(1):'overview');

